// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ContactRequestDirection.
const (
	Incoming ContactRequestDirection = "incoming"
	Outgoing ContactRequestDirection = "outgoing"
)

// Defines values for ContactRequestStatus.
const (
	Accepted ContactRequestStatus = "accepted"
	Declined ContactRequestStatus = "declined"
	Pending  ContactRequestStatus = "pending"
)

// Defines values for DevicePlatform.
const (
	DevicePlatformAndroid DevicePlatform = "android"
	DevicePlatformCli     DevicePlatform = "cli"
	DevicePlatformIos     DevicePlatform = "ios"
	DevicePlatformWeb     DevicePlatform = "web"
)

// Defines values for DeviceCreatePlatform.
const (
	DeviceCreatePlatformAndroid DeviceCreatePlatform = "android"
	DeviceCreatePlatformCli     DeviceCreatePlatform = "cli"
	DeviceCreatePlatformIos     DeviceCreatePlatform = "ios"
	DeviceCreatePlatformWeb     DeviceCreatePlatform = "web"
)

// Defines values for DeviceWithTokenPlatform.
const (
	Android DeviceWithTokenPlatform = "android"
	Cli     DeviceWithTokenPlatform = "cli"
	Ios     DeviceWithTokenPlatform = "ios"
	Web     DeviceWithTokenPlatform = "web"
)

// Defines values for HealthResponseStatus.
const (
	Healthy HealthResponseStatus = "healthy"
)

// Defines values for IdentityBackupAlgorithm.
const (
	AES256GCM IdentityBackupAlgorithm = "AES-256-GCM"
)

// Defines values for IdentityBackupKdf.
const (
	PBKDF2SHA256 IdentityBackupKdf = "PBKDF2-SHA256"
)

// ConflictError defines model for ConflictError.
type ConflictError struct {
	// CurrentVersion Current version on server
	CurrentVersion int `json:"currentVersion"`
	Error          struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Contact defines model for Contact.
type Contact struct {
	// CreatedAt When the contact relationship was established
	CreatedAt time.Time           `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`

	// Id Contact's user ID
	Id string `json:"id"`

	// Name Contact's display name
	Name string `json:"name"`

	// PublicKey Base64-encoded X25519 public key for encrypting locations
	PublicKey string `json:"publicKey"`
}

// ContactList defines model for ContactList.
type ContactList struct {
	Contacts []Contact `json:"contacts"`
}

// ContactRequest defines model for ContactRequest.
type ContactRequest struct {
	CreatedAt time.Time `json:"createdAt"`

	// Direction Whether this is an incoming or outgoing request
	Direction *ContactRequestDirection `json:"direction,omitempty"`

	// Email Email of the other user
	Email openapi_types.Email `json:"email"`

	// Id Request ID
	Id string `json:"id"`

	// Name Name of the other user (if available)
	Name   *string              `json:"name,omitempty"`
	Status ContactRequestStatus `json:"status"`
}

// ContactRequestDirection Whether this is an incoming or outgoing request
type ContactRequestDirection string

// ContactRequestStatus defines model for ContactRequest.Status.
type ContactRequestStatus string

// ContactRequestCreate defines model for ContactRequestCreate.
type ContactRequestCreate struct {
	// Email Email of the user to send request to
	Email openapi_types.Email `json:"email"`
}

// ContactRequestList defines model for ContactRequestList.
type ContactRequestList struct {
	Incoming []ContactRequest `json:"incoming"`
	Outgoing []ContactRequest `json:"outgoing"`
}

// Device defines model for Device.
type Device struct {
	CreatedAt time.Time `json:"createdAt"`

	// Id Device ID
	Id string `json:"id"`

	// IsCurrent Whether this is the current device making the request
	IsCurrent *bool `json:"isCurrent,omitempty"`

	// IsRevoked Whether this device has been revoked
	IsRevoked *bool     `json:"isRevoked,omitempty"`
	LastSeen  time.Time `json:"lastSeen"`

	// Name User-friendly device name
	Name     string         `json:"name"`
	Platform DevicePlatform `json:"platform"`
}

// DevicePlatform defines model for Device.Platform.
type DevicePlatform string

// DeviceCreate defines model for DeviceCreate.
type DeviceCreate struct {
	// Name User-friendly device name
	Name     string               `json:"name"`
	Platform DeviceCreatePlatform `json:"platform"`
}

// DeviceCreatePlatform defines model for DeviceCreate.Platform.
type DeviceCreatePlatform string

// DeviceList defines model for DeviceList.
type DeviceList struct {
	Devices []Device `json:"devices"`
}

// DeviceWithToken defines model for DeviceWithToken.
type DeviceWithToken struct {
	CreatedAt time.Time `json:"createdAt"`

	// Id Device ID
	Id string `json:"id"`

	// IsCurrent Whether this is the current device making the request
	IsCurrent *bool `json:"isCurrent,omitempty"`

	// IsRevoked Whether this device has been revoked
	IsRevoked *bool     `json:"isRevoked,omitempty"`
	LastSeen  time.Time `json:"lastSeen"`

	// Name User-friendly device name
	Name     string                  `json:"name"`
	Platform DeviceWithTokenPlatform `json:"platform"`

	// Token Device token for API authentication
	Token string `json:"token"`
}

// DeviceWithTokenPlatform defines model for DeviceWithToken.Platform.
type DeviceWithTokenPlatform string

// EncryptedLocation defines model for EncryptedLocation.
type EncryptedLocation struct {
	// Blob Base64-encoded NaCl box ciphertext.
	// Encrypted with sender's private key + recipient's public key.
	// Contains location hierarchy, optional named location, and timestamp.
	Blob string `json:"blob"`

	// FromUserId User ID who shared this location
	FromUserId string `json:"fromUserId"`

	// UpdatedAt When the location was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code Machine-readable error code
		Code string `json:"code"`

		// Message Human-readable error message
		Message string `json:"message"`
	} `json:"error"`
}

// GoogleLoginRequest defines model for GoogleLoginRequest.
type GoogleLoginRequest struct {
	// IdToken Google OAuth ID token
	IdToken string `json:"idToken"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`

	// Version Server version
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IdentityBackup defines model for IdentityBackup.
type IdentityBackup struct {
	// Algorithm Encryption algorithm
	Algorithm IdentityBackupAlgorithm `json:"algorithm"`

	// Iterations KDF iterations
	Iterations int `json:"iterations"`

	// Iv Base64-encoded IV (12 bytes)
	Iv string `json:"iv"`

	// Kdf Key derivation function
	Kdf IdentityBackupKdf `json:"kdf"`

	// Payload Base64-encoded ciphertext of encrypted keypair
	Payload string `json:"payload"`

	// Salt Base64-encoded salt (16 bytes)
	Salt string `json:"salt"`
}

// IdentityBackupAlgorithm Encryption algorithm
type IdentityBackupAlgorithm string

// IdentityBackupKdf Key derivation function
type IdentityBackupKdf string

// LocationList defines model for LocationList.
type LocationList struct {
	Locations []EncryptedLocation `json:"locations"`
}

// LocationShare defines model for LocationShare.
type LocationShare struct {
	// Blob Base64-encoded NaCl box ciphertext for this recipient
	Blob string `json:"blob"`

	// ToUserId User ID to share location with
	ToUserId string `json:"toUserId"`
}

// LocationShareRequest defines model for LocationShareRequest.
type LocationShareRequest struct {
	Locations []LocationShare `json:"locations"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// IsNewUser True if this is the user's first login
	IsNewUser *bool `json:"isNewUser,omitempty"`

	// Token Session token for API authentication
	Token string `json:"token"`
	User  User   `json:"user"`
}

// PublicKeyRequest defines model for PublicKeyRequest.
type PublicKeyRequest struct {
	// PublicKey Base64-encoded X25519 public key (32 bytes)
	PublicKey string `json:"publicKey"`
}

// User defines model for User.
type User struct {
	// CreatedAt Account creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Email User's email address
	Email openapi_types.Email `json:"email"`

	// HasIdentityBackup Whether user has stored an identity backup
	HasIdentityBackup *bool `json:"hasIdentityBackup,omitempty"`

	// HasUserData Whether user has stored encrypted user data
	HasUserData *bool `json:"hasUserData,omitempty"`

	// Id Unique user identifier
	Id string `json:"id"`

	// Name Display name
	Name string `json:"name"`

	// PublicKey Base64-encoded X25519 public key
	PublicKey *string `json:"publicKey,omitempty"`
}

// UserData defines model for UserData.
type UserData struct {
	// Blob Base64-encoded encrypted blob containing named locations,
	// contact permissions, and preferences.
	// Encrypted with NaCl box to self (user's own keypair).
	Blob *string `json:"blob,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`

	// Version Version number for optimistic concurrency
	Version int `json:"version"`
}

// UserDataUpdate defines model for UserDataUpdate.
type UserDataUpdate struct {
	// Blob Base64-encoded encrypted blob
	Blob string `json:"blob"`

	// Version Expected current version (for optimistic concurrency)
	Version int `json:"version"`
}

// ContactId defines model for contactId.
type ContactId = string

// DeviceId defines model for deviceId.
type DeviceId = string

// RequestId defines model for requestId.
type RequestId = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// LoginWithGoogleJSONRequestBody defines body for LoginWithGoogle for application/json ContentType.
type LoginWithGoogleJSONRequestBody = GoogleLoginRequest

// SendContactRequestJSONRequestBody defines body for SendContactRequest for application/json ContentType.
type SendContactRequestJSONRequestBody = ContactRequestCreate

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceCreate

// SetIdentityBackupJSONRequestBody defines body for SetIdentityBackup for application/json ContentType.
type SetIdentityBackupJSONRequestBody = IdentityBackup

// SetPublicKeyJSONRequestBody defines body for SetPublicKey for application/json ContentType.
type SetPublicKeyJSONRequestBody = PublicKeyRequest

// ShareLocationsJSONRequestBody defines body for ShareLocations for application/json ContentType.
type ShareLocationsJSONRequestBody = LocationShareRequest

// SetUserDataJSONRequestBody defines body for SetUserData for application/json ContentType.
type SetUserDataJSONRequestBody = UserDataUpdate

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DeleteAccount request
	DeleteAccount(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LoginWithGoogleWithBody request with any body
	LoginWithGoogleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	LoginWithGoogle(ctx context.Context, body LoginWithGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Logout request
	Logout(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListContacts request
	ListContacts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendContactRequestWithBody request with any body
	SendContactRequestWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SendContactRequest(ctx context.Context, body SendContactRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListContactRequests request
	ListContactRequests(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelContactRequest request
	CancelContactRequest(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AcceptContactRequest request
	AcceptContactRequest(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeclineContactRequest request
	DeclineContactRequest(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RemoveContact request
	RemoveContact(ctx context.Context, contactId ContactId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDevices request
	ListDevices(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterDeviceWithBody request with any body
	RegisterDeviceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RegisterDevice(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeDevice request
	RevokeDevice(ctx context.Context, deviceId DeviceId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIdentityBackup request
	GetIdentityBackup(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetIdentityBackupWithBody request with any body
	SetIdentityBackupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetIdentityBackup(ctx context.Context, body SetIdentityBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetPublicKeyWithBody request with any body
	SetPublicKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetPublicKey(ctx context.Context, body SetPublicKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetLocations request
	GetLocations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ShareLocationsWithBody request with any body
	ShareLocationsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ShareLocations(ctx context.Context, body ShareLocationsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCurrentUser request
	GetCurrentUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserData request
	GetUserData(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetUserDataWithBody request with any body
	SetUserDataWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetUserData(ctx context.Context, body SetUserDataJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DeleteAccount(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAccountRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LoginWithGoogleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginWithGoogleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LoginWithGoogle(ctx context.Context, body LoginWithGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginWithGoogleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Logout(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLogoutRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListContacts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListContactsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendContactRequestWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendContactRequestRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendContactRequest(ctx context.Context, body SendContactRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendContactRequestRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListContactRequests(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListContactRequestsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelContactRequest(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelContactRequestRequest(c.Server, requestId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AcceptContactRequest(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAcceptContactRequestRequest(c.Server, requestId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeclineContactRequest(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeclineContactRequestRequest(c.Server, requestId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RemoveContact(ctx context.Context, contactId ContactId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRemoveContactRequest(c.Server, contactId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListDevices(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDevicesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterDeviceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterDeviceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterDevice(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterDeviceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeDevice(ctx context.Context, deviceId DeviceId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeDeviceRequest(c.Server, deviceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetIdentityBackup(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIdentityBackupRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetIdentityBackupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetIdentityBackupRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetIdentityBackup(ctx context.Context, body SetIdentityBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetIdentityBackupRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetPublicKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetPublicKeyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetPublicKey(ctx context.Context, body SetPublicKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetPublicKeyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetLocations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLocationsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ShareLocationsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewShareLocationsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ShareLocations(ctx context.Context, body ShareLocationsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewShareLocationsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCurrentUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCurrentUserRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUserData(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserDataRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetUserDataWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetUserDataRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetUserData(ctx context.Context, body SetUserDataJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetUserDataRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDeleteAccountRequest generates requests for DeleteAccount
func NewDeleteAccountRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/account")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLoginWithGoogleRequest calls the generic LoginWithGoogle builder with application/json body
func NewLoginWithGoogleRequest(server string, body LoginWithGoogleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLoginWithGoogleRequestWithBody(server, "application/json", bodyReader)
}

// NewLoginWithGoogleRequestWithBody generates requests for LoginWithGoogle with any type of body
func NewLoginWithGoogleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/google")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewLogoutRequest generates requests for Logout
func NewLogoutRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/logout")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListContactsRequest generates requests for ListContacts
func NewListContactsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/contacts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSendContactRequestRequest calls the generic SendContactRequest builder with application/json body
func NewSendContactRequestRequest(server string, body SendContactRequestJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendContactRequestRequestWithBody(server, "application/json", bodyReader)
}

// NewSendContactRequestRequestWithBody generates requests for SendContactRequest with any type of body
func NewSendContactRequestRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/contacts/request")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListContactRequestsRequest generates requests for ListContactRequests
func NewListContactRequestsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/contacts/requests")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCancelContactRequestRequest generates requests for CancelContactRequest
func NewCancelContactRequestRequest(server string, requestId RequestId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "requestId", runtime.ParamLocationPath, requestId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/contacts/requests/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAcceptContactRequestRequest generates requests for AcceptContactRequest
func NewAcceptContactRequestRequest(server string, requestId RequestId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "requestId", runtime.ParamLocationPath, requestId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/contacts/requests/%s/accept", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeclineContactRequestRequest generates requests for DeclineContactRequest
func NewDeclineContactRequestRequest(server string, requestId RequestId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "requestId", runtime.ParamLocationPath, requestId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/contacts/requests/%s/decline", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRemoveContactRequest generates requests for RemoveContact
func NewRemoveContactRequest(server string, contactId ContactId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "contactId", runtime.ParamLocationPath, contactId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/contacts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDevicesRequest generates requests for ListDevices
func NewListDevicesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/devices")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRegisterDeviceRequest calls the generic RegisterDevice builder with application/json body
func NewRegisterDeviceRequest(server string, body RegisterDeviceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterDeviceRequestWithBody(server, "application/json", bodyReader)
}

// NewRegisterDeviceRequestWithBody generates requests for RegisterDevice with any type of body
func NewRegisterDeviceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/devices")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRevokeDeviceRequest generates requests for RevokeDevice
func NewRevokeDeviceRequest(server string, deviceId DeviceId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "deviceId", runtime.ParamLocationPath, deviceId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/devices/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetIdentityBackupRequest generates requests for GetIdentityBackup
func NewGetIdentityBackupRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/identity/backup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSetIdentityBackupRequest calls the generic SetIdentityBackup builder with application/json body
func NewSetIdentityBackupRequest(server string, body SetIdentityBackupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetIdentityBackupRequestWithBody(server, "application/json", bodyReader)
}

// NewSetIdentityBackupRequestWithBody generates requests for SetIdentityBackup with any type of body
func NewSetIdentityBackupRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/identity/backup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSetPublicKeyRequest calls the generic SetPublicKey builder with application/json body
func NewSetPublicKeyRequest(server string, body SetPublicKeyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetPublicKeyRequestWithBody(server, "application/json", bodyReader)
}

// NewSetPublicKeyRequestWithBody generates requests for SetPublicKey with any type of body
func NewSetPublicKeyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/identity/public-key")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetLocationsRequest generates requests for GetLocations
func NewGetLocationsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/locations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewShareLocationsRequest calls the generic ShareLocations builder with application/json body
func NewShareLocationsRequest(server string, body ShareLocationsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewShareLocationsRequestWithBody(server, "application/json", bodyReader)
}

// NewShareLocationsRequestWithBody generates requests for ShareLocations with any type of body
func NewShareLocationsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/locations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetCurrentUserRequest generates requests for GetCurrentUser
func NewGetCurrentUserRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUserDataRequest generates requests for GetUserData
func NewGetUserDataRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user-data")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSetUserDataRequest calls the generic SetUserData builder with application/json body
func NewSetUserDataRequest(server string, body SetUserDataJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetUserDataRequestWithBody(server, "application/json", bodyReader)
}

// NewSetUserDataRequestWithBody generates requests for SetUserData with any type of body
func NewSetUserDataRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user-data")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DeleteAccountWithResponse request
	DeleteAccountWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteAccountResponse, error)

	// LoginWithGoogleWithBodyWithResponse request with any body
	LoginWithGoogleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginWithGoogleResponse, error)

	LoginWithGoogleWithResponse(ctx context.Context, body LoginWithGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginWithGoogleResponse, error)

	// LogoutWithResponse request
	LogoutWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*LogoutResponse, error)

	// ListContactsWithResponse request
	ListContactsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListContactsResponse, error)

	// SendContactRequestWithBodyWithResponse request with any body
	SendContactRequestWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendContactRequestResponse, error)

	SendContactRequestWithResponse(ctx context.Context, body SendContactRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*SendContactRequestResponse, error)

	// ListContactRequestsWithResponse request
	ListContactRequestsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListContactRequestsResponse, error)

	// CancelContactRequestWithResponse request
	CancelContactRequestWithResponse(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*CancelContactRequestResponse, error)

	// AcceptContactRequestWithResponse request
	AcceptContactRequestWithResponse(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*AcceptContactRequestResponse, error)

	// DeclineContactRequestWithResponse request
	DeclineContactRequestWithResponse(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*DeclineContactRequestResponse, error)

	// RemoveContactWithResponse request
	RemoveContactWithResponse(ctx context.Context, contactId ContactId, reqEditors ...RequestEditorFn) (*RemoveContactResponse, error)

	// ListDevicesWithResponse request
	ListDevicesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDevicesResponse, error)

	// RegisterDeviceWithBodyWithResponse request with any body
	RegisterDeviceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error)

	RegisterDeviceWithResponse(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error)

	// RevokeDeviceWithResponse request
	RevokeDeviceWithResponse(ctx context.Context, deviceId DeviceId, reqEditors ...RequestEditorFn) (*RevokeDeviceResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// GetIdentityBackupWithResponse request
	GetIdentityBackupWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetIdentityBackupResponse, error)

	// SetIdentityBackupWithBodyWithResponse request with any body
	SetIdentityBackupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetIdentityBackupResponse, error)

	SetIdentityBackupWithResponse(ctx context.Context, body SetIdentityBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*SetIdentityBackupResponse, error)

	// SetPublicKeyWithBodyWithResponse request with any body
	SetPublicKeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetPublicKeyResponse, error)

	SetPublicKeyWithResponse(ctx context.Context, body SetPublicKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*SetPublicKeyResponse, error)

	// GetLocationsWithResponse request
	GetLocationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetLocationsResponse, error)

	// ShareLocationsWithBodyWithResponse request with any body
	ShareLocationsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ShareLocationsResponse, error)

	ShareLocationsWithResponse(ctx context.Context, body ShareLocationsJSONRequestBody, reqEditors ...RequestEditorFn) (*ShareLocationsResponse, error)

	// GetCurrentUserWithResponse request
	GetCurrentUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCurrentUserResponse, error)

	// GetUserDataWithResponse request
	GetUserDataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserDataResponse, error)

	// SetUserDataWithBodyWithResponse request with any body
	SetUserDataWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetUserDataResponse, error)

	SetUserDataWithResponse(ctx context.Context, body SetUserDataJSONRequestBody, reqEditors ...RequestEditorFn) (*SetUserDataResponse, error)
}

type DeleteAccountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r DeleteAccountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAccountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LoginWithGoogleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LoginResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r LoginWithGoogleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LoginWithGoogleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LogoutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r LogoutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LogoutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListContactsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ContactList
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r ListContactsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListContactsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SendContactRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ContactRequest
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *Error
	JSON409      *Error
}

// Status returns HTTPResponse.Status
func (r SendContactRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendContactRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListContactRequestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ContactRequestList
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r ListContactRequestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListContactRequestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CancelContactRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r CancelContactRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelContactRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AcceptContactRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Contact
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r AcceptContactRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AcceptContactRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeclineContactRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r DeclineContactRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeclineContactRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RemoveContactResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r RemoveContactResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RemoveContactResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListDevicesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeviceList
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r ListDevicesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDevicesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RegisterDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *DeviceWithToken
	JSON400      *BadRequest
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r RegisterDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RevokeDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r RevokeDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetIdentityBackupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *IdentityBackup
	JSON401      *Unauthorized
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r GetIdentityBackupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIdentityBackupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SetIdentityBackupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r SetIdentityBackupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetIdentityBackupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SetPublicKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r SetPublicKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetPublicKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetLocationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LocationList
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r GetLocationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLocationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ShareLocationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r ShareLocationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ShareLocationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCurrentUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *User
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r GetCurrentUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCurrentUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserDataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserData
	JSON401      *Unauthorized
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r GetUserDataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserDataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SetUserDataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserData
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON409      *ConflictError
}

// Status returns HTTPResponse.Status
func (r SetUserDataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetUserDataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// DeleteAccountWithResponse request returning *DeleteAccountResponse
func (c *ClientWithResponses) DeleteAccountWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteAccountResponse, error) {
	rsp, err := c.DeleteAccount(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAccountResponse(rsp)
}

// LoginWithGoogleWithBodyWithResponse request with arbitrary body returning *LoginWithGoogleResponse
func (c *ClientWithResponses) LoginWithGoogleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginWithGoogleResponse, error) {
	rsp, err := c.LoginWithGoogleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginWithGoogleResponse(rsp)
}

func (c *ClientWithResponses) LoginWithGoogleWithResponse(ctx context.Context, body LoginWithGoogleJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginWithGoogleResponse, error) {
	rsp, err := c.LoginWithGoogle(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginWithGoogleResponse(rsp)
}

// LogoutWithResponse request returning *LogoutResponse
func (c *ClientWithResponses) LogoutWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*LogoutResponse, error) {
	rsp, err := c.Logout(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLogoutResponse(rsp)
}

// ListContactsWithResponse request returning *ListContactsResponse
func (c *ClientWithResponses) ListContactsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListContactsResponse, error) {
	rsp, err := c.ListContacts(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListContactsResponse(rsp)
}

// SendContactRequestWithBodyWithResponse request with arbitrary body returning *SendContactRequestResponse
func (c *ClientWithResponses) SendContactRequestWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendContactRequestResponse, error) {
	rsp, err := c.SendContactRequestWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendContactRequestResponse(rsp)
}

func (c *ClientWithResponses) SendContactRequestWithResponse(ctx context.Context, body SendContactRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*SendContactRequestResponse, error) {
	rsp, err := c.SendContactRequest(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendContactRequestResponse(rsp)
}

// ListContactRequestsWithResponse request returning *ListContactRequestsResponse
func (c *ClientWithResponses) ListContactRequestsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListContactRequestsResponse, error) {
	rsp, err := c.ListContactRequests(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListContactRequestsResponse(rsp)
}

// CancelContactRequestWithResponse request returning *CancelContactRequestResponse
func (c *ClientWithResponses) CancelContactRequestWithResponse(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*CancelContactRequestResponse, error) {
	rsp, err := c.CancelContactRequest(ctx, requestId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelContactRequestResponse(rsp)
}

// AcceptContactRequestWithResponse request returning *AcceptContactRequestResponse
func (c *ClientWithResponses) AcceptContactRequestWithResponse(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*AcceptContactRequestResponse, error) {
	rsp, err := c.AcceptContactRequest(ctx, requestId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAcceptContactRequestResponse(rsp)
}

// DeclineContactRequestWithResponse request returning *DeclineContactRequestResponse
func (c *ClientWithResponses) DeclineContactRequestWithResponse(ctx context.Context, requestId RequestId, reqEditors ...RequestEditorFn) (*DeclineContactRequestResponse, error) {
	rsp, err := c.DeclineContactRequest(ctx, requestId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeclineContactRequestResponse(rsp)
}

// RemoveContactWithResponse request returning *RemoveContactResponse
func (c *ClientWithResponses) RemoveContactWithResponse(ctx context.Context, contactId ContactId, reqEditors ...RequestEditorFn) (*RemoveContactResponse, error) {
	rsp, err := c.RemoveContact(ctx, contactId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRemoveContactResponse(rsp)
}

// ListDevicesWithResponse request returning *ListDevicesResponse
func (c *ClientWithResponses) ListDevicesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDevicesResponse, error) {
	rsp, err := c.ListDevices(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDevicesResponse(rsp)
}

// RegisterDeviceWithBodyWithResponse request with arbitrary body returning *RegisterDeviceResponse
func (c *ClientWithResponses) RegisterDeviceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error) {
	rsp, err := c.RegisterDeviceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterDeviceResponse(rsp)
}

func (c *ClientWithResponses) RegisterDeviceWithResponse(ctx context.Context, body RegisterDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterDeviceResponse, error) {
	rsp, err := c.RegisterDevice(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterDeviceResponse(rsp)
}

// RevokeDeviceWithResponse request returning *RevokeDeviceResponse
func (c *ClientWithResponses) RevokeDeviceWithResponse(ctx context.Context, deviceId DeviceId, reqEditors ...RequestEditorFn) (*RevokeDeviceResponse, error) {
	rsp, err := c.RevokeDevice(ctx, deviceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeDeviceResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// GetIdentityBackupWithResponse request returning *GetIdentityBackupResponse
func (c *ClientWithResponses) GetIdentityBackupWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetIdentityBackupResponse, error) {
	rsp, err := c.GetIdentityBackup(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIdentityBackupResponse(rsp)
}

// SetIdentityBackupWithBodyWithResponse request with arbitrary body returning *SetIdentityBackupResponse
func (c *ClientWithResponses) SetIdentityBackupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetIdentityBackupResponse, error) {
	rsp, err := c.SetIdentityBackupWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetIdentityBackupResponse(rsp)
}

func (c *ClientWithResponses) SetIdentityBackupWithResponse(ctx context.Context, body SetIdentityBackupJSONRequestBody, reqEditors ...RequestEditorFn) (*SetIdentityBackupResponse, error) {
	rsp, err := c.SetIdentityBackup(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetIdentityBackupResponse(rsp)
}

// SetPublicKeyWithBodyWithResponse request with arbitrary body returning *SetPublicKeyResponse
func (c *ClientWithResponses) SetPublicKeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetPublicKeyResponse, error) {
	rsp, err := c.SetPublicKeyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetPublicKeyResponse(rsp)
}

func (c *ClientWithResponses) SetPublicKeyWithResponse(ctx context.Context, body SetPublicKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*SetPublicKeyResponse, error) {
	rsp, err := c.SetPublicKey(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetPublicKeyResponse(rsp)
}

// GetLocationsWithResponse request returning *GetLocationsResponse
func (c *ClientWithResponses) GetLocationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetLocationsResponse, error) {
	rsp, err := c.GetLocations(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLocationsResponse(rsp)
}

// ShareLocationsWithBodyWithResponse request with arbitrary body returning *ShareLocationsResponse
func (c *ClientWithResponses) ShareLocationsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ShareLocationsResponse, error) {
	rsp, err := c.ShareLocationsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseShareLocationsResponse(rsp)
}

func (c *ClientWithResponses) ShareLocationsWithResponse(ctx context.Context, body ShareLocationsJSONRequestBody, reqEditors ...RequestEditorFn) (*ShareLocationsResponse, error) {
	rsp, err := c.ShareLocations(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseShareLocationsResponse(rsp)
}

// GetCurrentUserWithResponse request returning *GetCurrentUserResponse
func (c *ClientWithResponses) GetCurrentUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCurrentUserResponse, error) {
	rsp, err := c.GetCurrentUser(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCurrentUserResponse(rsp)
}

// GetUserDataWithResponse request returning *GetUserDataResponse
func (c *ClientWithResponses) GetUserDataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserDataResponse, error) {
	rsp, err := c.GetUserData(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserDataResponse(rsp)
}

// SetUserDataWithBodyWithResponse request with arbitrary body returning *SetUserDataResponse
func (c *ClientWithResponses) SetUserDataWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetUserDataResponse, error) {
	rsp, err := c.SetUserDataWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetUserDataResponse(rsp)
}

func (c *ClientWithResponses) SetUserDataWithResponse(ctx context.Context, body SetUserDataJSONRequestBody, reqEditors ...RequestEditorFn) (*SetUserDataResponse, error) {
	rsp, err := c.SetUserData(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetUserDataResponse(rsp)
}

// ParseDeleteAccountResponse parses an HTTP response from a DeleteAccountWithResponse call
func ParseDeleteAccountResponse(rsp *http.Response) (*DeleteAccountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAccountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseLoginWithGoogleResponse parses an HTTP response from a LoginWithGoogleWithResponse call
func ParseLoginWithGoogleResponse(rsp *http.Response) (*LoginWithGoogleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LoginWithGoogleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LoginResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseLogoutResponse parses an HTTP response from a LogoutWithResponse call
func ParseLogoutResponse(rsp *http.Response) (*LogoutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LogoutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseListContactsResponse parses an HTTP response from a ListContactsWithResponse call
func ParseListContactsResponse(rsp *http.Response) (*ListContactsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListContactsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ContactList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseSendContactRequestResponse parses an HTTP response from a SendContactRequestWithResponse call
func ParseSendContactRequestResponse(rsp *http.Response) (*SendContactRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendContactRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ContactRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseListContactRequestsResponse parses an HTTP response from a ListContactRequestsWithResponse call
func ParseListContactRequestsResponse(rsp *http.Response) (*ListContactRequestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListContactRequestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ContactRequestList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseCancelContactRequestResponse parses an HTTP response from a CancelContactRequestWithResponse call
func ParseCancelContactRequestResponse(rsp *http.Response) (*CancelContactRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelContactRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseAcceptContactRequestResponse parses an HTTP response from a AcceptContactRequestWithResponse call
func ParseAcceptContactRequestResponse(rsp *http.Response) (*AcceptContactRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AcceptContactRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Contact
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseDeclineContactRequestResponse parses an HTTP response from a DeclineContactRequestWithResponse call
func ParseDeclineContactRequestResponse(rsp *http.Response) (*DeclineContactRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeclineContactRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseRemoveContactResponse parses an HTTP response from a RemoveContactWithResponse call
func ParseRemoveContactResponse(rsp *http.Response) (*RemoveContactResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RemoveContactResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListDevicesResponse parses an HTTP response from a ListDevicesWithResponse call
func ParseListDevicesResponse(rsp *http.Response) (*ListDevicesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDevicesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeviceList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseRegisterDeviceResponse parses an HTTP response from a RegisterDeviceWithResponse call
func ParseRegisterDeviceResponse(rsp *http.Response) (*RegisterDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest DeviceWithToken
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseRevokeDeviceResponse parses an HTTP response from a RevokeDeviceWithResponse call
func ParseRevokeDeviceResponse(rsp *http.Response) (*RevokeDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetIdentityBackupResponse parses an HTTP response from a GetIdentityBackupWithResponse call
func ParseGetIdentityBackupResponse(rsp *http.Response) (*GetIdentityBackupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIdentityBackupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest IdentityBackup
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseSetIdentityBackupResponse parses an HTTP response from a SetIdentityBackupWithResponse call
func ParseSetIdentityBackupResponse(rsp *http.Response) (*SetIdentityBackupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetIdentityBackupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseSetPublicKeyResponse parses an HTTP response from a SetPublicKeyWithResponse call
func ParseSetPublicKeyResponse(rsp *http.Response) (*SetPublicKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetPublicKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetLocationsResponse parses an HTTP response from a GetLocationsWithResponse call
func ParseGetLocationsResponse(rsp *http.Response) (*GetLocationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLocationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LocationList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseShareLocationsResponse parses an HTTP response from a ShareLocationsWithResponse call
func ParseShareLocationsResponse(rsp *http.Response) (*ShareLocationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ShareLocationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetCurrentUserResponse parses an HTTP response from a GetCurrentUserWithResponse call
func ParseGetCurrentUserResponse(rsp *http.Response) (*GetCurrentUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCurrentUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetUserDataResponse parses an HTTP response from a GetUserDataWithResponse call
func ParseGetUserDataResponse(rsp *http.Response) (*GetUserDataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserDataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseSetUserDataResponse parses an HTTP response from a SetUserDataWithResponse call
func ParseSetUserDataResponse(rsp *http.Response) (*SetUserDataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetUserDataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ConflictError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}
